In [16]:
import torch


In [17]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

张量表示一个数值组成的数组，这个数组可能就多个维度

In [18]:
x.shape

torch.Size([12])

In [19]:
x.numel()

12

通过张量的shape属性来访问张量的形状和元素总数

In [21]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

改变一个张量的形状不改变元素数量和元素值，调用reshape函数

In [22]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
torch.ones((3, 5, 3))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [25]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

使用全0，或其他常量或特定分布中随机采样的数字

In [27]:
x = torch.tensor([1.0, 2, 4, 8])#1.0可以创建一个浮点数组
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]))

常见的标准算术运算符（+，-，*，/,**）可以被升级为按元素运算

In [31]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Z = torch.randn(3, 4)
torch.cat((X,Y),dim=0), torch.cat((X,Y), dim=1), torch.cat((X, Y, Z), dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  2.0000,  1.0000,  4.0000,  3.0000,
          -2.9786,  1.2872,  1.2041,  0.0301],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  1.0000,  2.0000,  3.0000,  4.0000,
          -0.8250, -0.7935, -0.6002,  0.1136],
         [ 8.0000,  9.0000, 10.0000, 11.0000,  4.0000,  3.0000,  2.0000,  1.0000,
           0.1238, -0.8344, -1.1432, -1.3913]]))

可以把多个张量结合(concatenate)到一起

In [32]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

即使形状不同，我们仍然可以通过调用 广播机制 （broadcasting mechanism） 来执行按元素操作,

In [34]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [35]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

可以用 [-1] 选择X最后一行元素，可以用 [1:3] 选择第二行和第三行元素。
除读取外，我们还可以通过指定索引来将元素写入矩阵
为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值

In [38]:
A=X.numpy()
B=torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

转化为numpy张量