通过指定两个分量m和 n来创建一个形状为m×n的矩阵

In [1]:
import torch
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [2]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [5]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()#通过分配新的内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为哈达玛积（Hadamard product）（数学符号⊙）

In [6]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

计算其元素的和

In [8]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和.指定张量沿哪一个轴来通过求和降低维度

In [9]:
A = torch.arange(40).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [11]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [12]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [13]:
A.sum(axis=[0, 1]).shape

torch.Size([4])

一个与求和相关的量是平均值（mean或average）

In [20]:
A = torch.arange(40.0).reshape(2, 5, 4)
A.mean()

tensor(19.5000)

计算总和或均值时保持轴数不变,通过广播将A除以sum_A

In [22]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, A/sum_A

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
          [0.1000, 0.1111, 0.1200, 0.1273],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.3000, 0.2889, 0.2800, 0.2727],
          [0.4000, 0.3778, 0.3600, 0.3455]],
 
         [[0.1429, 0.1448, 0.1467, 0.1484],
          [0.1714, 0.1724, 0.1733, 0.1742],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.2286, 0.2276, 0.2267, 0.2258],
          [0.2571, 0.2552, 0.2533, 0.2516]]]))

某个轴计算A元素的累积总和

In [23]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

点积是相同位置的按元素乘积的和

In [25]:
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y), torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

矩阵向量积Ax是一个长度为m的列向量，其第i个元素是点积aiTx

In [32]:
A=torch.arange(20.0).reshape(5,4)
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n×m矩阵

In [33]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2 范数是向量元素平方和的平方根;L1 范数，它表示为向量元素的绝对值之和;弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素平方和的平方根(F范数最常用)

In [34]:
torch.norm(torch.ones((4, 9)))#f范数

tensor(6.)

In [36]:
u=torch.tensor([3.0, -4.0])
torch.abs(u).sum()#L1范数

tensor(7.)

In [37]:
torch.norm(u)#L2范数

tensor(5.)